<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.65.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libs\Application\Application.csproj" />
    <ProjectReference Include="..\IntegrationTests.Helper\IntegrationTests.Helper.csproj" />
  </ItemGroup>
</Project>
